### ISSUE TITLE
easyjson: command not found

### ISSUE THREAD

**Issue by brandonsturgeon** [mailru/easyjson#143]
Using ubuntu 16.04

Properly set my GOPATH to `$PWD`

run `go get -u github.com/mailru/easyjson/...`

and then `easyjson`

and I get `easyjson: command not found`

Instructions are limited about what a "full Go build environment" means.

Please help.

**Comment by brandonsturgeon** [comment]
I had to run `./bin/easyjson -all src/my_project/main.go` but it works now

**Comment by rvasily** [comment]
All `go get -u` programs install to $GOPATH/bin
To have access to ther directli you have to add $GOPATH/bin to your PATH

**Comment by brandonsturgeon** [comment]
Gotcha, thank you :)

**Comment by ntoskrnl** [comment]
For those who are still having this issue:
I had similar problem and turned out to be my mistake.
Instead of 
`go get -u github.com/mailru/easyjson/...`
 I wrote 
`go get -u github.com/mailru/easyjson/` (without trailing `...`). 

This is important. It took me some time to figure out a problem. In fact, I had to build easyjson executable myself and copy it to `$GOPATH/bin`.

**Comment by eekrupin** [comment]
Work for me: "go get -u github.com/mailru/easyjson/..."

**Comment by Achint08** [comment]
Try this for zsh.

```
export GOPATH=/Users/username/go
export PATH=$GOPATH/bin:$PATH
```
