### ISSUE TITLE
Optional type meaning

### ISSUE THREAD

**Issue by pashaosipyants** [mailru/easyjson#203]
Could u clarify, please, Optional type meaning
Cause as i understood after reading docs, IsDefined method switch on/off "omitemty" tag
But really it just manage adding or not field, if it has omitempty tag

So that, e.g.

```
type MyInt int

func (MyInt) IsDefined() bool {
	return false
}

type Json struct {
	X MyInt `json:",omitempty"`
}
```

won't print  X field even it is not empty. Does this behavior supposed to be?
If that is correct, why does it need omitempty tag?

**Comment by shmel1k** [comment]
Optional type is used to clearly understand if the value inside 'Opt' is set.

For example, you have 'boolean' variable. By default it is set to 'false'. If you have such kind of structure like

```go
type A struct {
    Field bool `json:",omitempty"`
}
```

the JSON serializer will hide it because of it's default 'false' value. So in order to understand when variable is set 'Opt' type should be used :)
