### ISSUE TITLE
Embedded structs

### ISSUE THREAD

**Issue by kipal** [mailru/easyjson#21]
Hi,

I have embedded structs and I get this problem "eaysjson_decode_... redeclared in this block ... previous declaration at ..."
I've noticed that structs are also copied where they were embedded. Do you have any options to turn this off?
Btw.: I tried to run easyjson file by file, and for the whole directory too, but I've got the same problem.

**Comment by vstarodub** [comment]
The embedded structs are not the issue here, the issue is due to generation of the same marshallers for the same structs in different files. I'll fix that.

As for the second part, I don't quite understand what exactly you are suggesting to be able to turn off. Can you provide a snippet of the generated code you are having problems with or some other example?

**Comment by kipal** [comment]
Sorry, you're right. So, just the first part is the issue here. :)

**Comment by bfitzsimmons** [comment]
I'm getting the same error when my structs have custom Marshal and Unmarshal methods.

**Comment by vstarodub** [comment]
@bfitzsimmons Could you provide an example?
