### ISSUE TITLE
Required/Optional fields

### ISSUE THREAD

**Issue by mkabischev** [mailru/easyjson#24]
For example we have such struct:
```go
type SomeStruct struct {
    Key1 string
    Key2 string
    Key3 *string
```
where key3 is nullable, because zero-value is valid value for it.
And all these examples can be successfully unmarshalled:
```json
{
	"key1": "value1",
	"key2": "value2",
	"key3": "value3"
}
{
	"key1": "value1",
	"key2": "value2",
        "key3": ""
}
{
	"key1": "value1",
	"key2": "value2",
}
```
But if key1 or key2 is missed then unmarshall must return an error.

What do you think about such mode?

**Comment by vstarodub** [comment]
Hi! In fact, it seems I'll soon have to implement required field logic (and possibly, custom default values) for my own use-cases. In my cases it also seems that most of the fields will be optional.

I'm not a big fan of using pointers for optional types. Apart from blurring the pointer semantics, they force an otherwise unneccessary allocation which is in conflict with performance goals: serialization becomes slower, a lot of garbage is created on heap, and, e.g. a 32-bit int occupies at least four times the space.

Also, pointers to primitive types make the using the structs more complex. You can't just write "&5", you'll need to write instead something like "easyjson.Int(5)" or "v.F = new(int); *v.F = 5" which is rather cumbersome.

I'm planning to implement a `json:",required"` or maybe even `required:"true"` annotation which will allow to implement behavior similar to what you suggested without making the user code any more complex. Will that be of any help?

**Comment by mkabischev** [comment]
Good points about pointers. I like you idea with annotation and it doesn`t really conflict with pointer usage.

Have you started working on implementation? I`d like to try to do it myself and send it as PR.

**Comment by vstarodub** [comment]
Implemented in Mike's PR.
