### ISSUE TITLE
(Un)Marshal string to []byte

### ISSUE THREAD

**Issue by dAdAbird** [mailru/easyjson#32]
Is there any possibilities to unmarshal `json-string` to `[]byte` and vice versa? Am I right that currently no?
It can be useful to reduce memory allocations and avoid unnecessary `sting <-> []byte` converting in application.

Anyway, I have a dummy fix for that and can formalize it in PR.

But the question is in what way to tell parser to process []byte that way. With cli falg e.g. `-stringtobytes` or better with tag e.g. `easyjson:"string"` for desired fields:

``` go
type T struct {
    name []byte `easyjson:"string"`
    ...
}
```

What do you think?

**Comment by vstarodub** [comment]
Hi! IMO, a tag is definitely better than a command-line option since it would work on a per-field basis. I'd probably go with `json:",string"` in this case, since it's already used for ints and seems to do nothing on []byte in the standard marshaler.

Note that if the string contains escape chars, an allocation would still be required for unmarshalling. Marshalling is able to amortize all the allocations, so all this is somewhat irrelevant for marshaller.

Another option would be to make a new type (e.g. `type ZeroCopyString string`) and write unmarshaler for it, you can use UnsafeString() lexer method to have a string pointing to the original buffer. This can already be done by the application and it might be preferable, depending on your scenario.

And the last option is to implement something like "very unsafe" mode of operation, where all the returned strings would point to the original buffer. I'm definitely against doing this by default, but it seems that there's a lot of code where this would be ok or even preferable.

**Comment by rvasily** [comment]
i think json.RawMessages is whay you want
